### ISSUE TITLE
More advanced timer slider

### ISSUE THREAD

**Issue by DevSecNinja** [DevSecNinja/ESPHome-Zehnder-RF#14]
To further enhance the timer slider, I would like the slider to automatically go down a minute until it reaches 0.

## ChatGPT inspiration

To modify the given ESPHome number template to meet your requirements, you will need to create a timer that decrements the value of the number template every minute until it reaches zero. Additionally, you have to ensure that the `setSpeed()` function is only triggered when the user manually sets the timer, not when it's automatically decremented by the system.  
   
Here's how you can implement these changes:  
   
1. **Create a global variable** to store the original set value of the timer.  
2. **Modify the `set_action`** to update this global variable when the timer is manually set.  
3. **Create an interval action** that decrements the timer value every minute, checking if the timer was set manually using the global variable.  
   
Below is the modified ESPHome configuration:  
   
```yaml  
globals:  
  - id: timer_value  
    type: int  
    restore_value: no  
    initial_value: '0'  
   
number:  
  - platform: template  
    id: ${device_id}_timer_in_minutes  
    name: "Timer in minutes"  
    optimistic: true  
    min_value: 0  
    max_value: 60  
    initial_value: 0  
    step: 1  
    set_action:  
      then:  
        - if:  
            condition:  
              lambda: 'return x != id(timer_value);'  
            then:  
              - light.turn_on: "${device_id}_status_led"  
              - delay: 500ms  
              - light.turn_off: "${device_id}_status_led"  
              - lambda: |-  
                  ${device_id}_ventilation->setSpeed(4, x);  
                  id(timer_value) = x;  
        - number.set:  
            id: ${device_id}_timer_in_minutes  
            value: !lambda 'return id(timer_value);'  
   
interval:  
  - interval: 1min  
    then:  
      - if:  
          condition:  
            lambda: 'return id(timer_value) > 0;'  
          then:  
            - lambda: |-  
                id(timer_value) -= 1;  
                id(${device_id}_timer_in_minutes).publish_state(id(timer_value));  
```  
   
Explanation:  
- **Globals**: A global variable `timer_value` is used to store the current value of the timer when it's set by the user.  
- **Number Component Set Action**: The `set_action` now includes a condition to check if the value `x` (new timer value) is different from the global `timer_value`. This ensures that `setSpeed()` is only called when the user changes the timer value, and not during the automatic countdown.  
- **Interval Action**: Every minute, the `interval` action checks if `timer_value` is greater than 0. If true, it decrements the `timer_value` by 1 and updates the number state using `publish_state()`.  
   
This setup ensures that the timer counts down every minute and that the `setSpeed()` function is only called when the user sets a new timer value, not during the countdown. Adjust the `interval` and `lambda` expressions according to your specific requirements and variable names.
